export class ArcForm {
  client: string;
  clientCode: string;
  clientLead: string;
  hokAccountLead: string;
  hokMediaLead: string;
  primaryConversionGoal: string;
  secondaryConversionGoal: string;
  clickCookieWindow: string;
  impressionCookieWindow: string;
  totalActualBudget: string;
  plannedInvestment: string;
  contingency: string;
  startDate: string;
  endDate: string;
  country: string;
  currency: string;
  bau: string;
  lastUpdated: string;

  constructor() {
    this.client = '';
    this.clientCode = '';
    this.clientLead = '';
    this.hokAccountLead = '';
    this.hokMediaLead = '';
    this.primaryConversionGoal = '';
    this.secondaryConversionGoal = '';
    this.clickCookieWindow = '';
    this.impressionCookieWindow = '';
    this.totalActualBudget = '';
    this.plannedInvestment = '';
    this.contingency = '';
    this.startDate = '';
    this.endDate = '';
    this.country = '';
    this.currency = '';
    this.bau = '';
    this.lastUpdated = '';
  }
}

export class ArcPublisher {
  publisher: string;
  producta: string;
  targetinga: string;
  targetingb: string;
  campaign: string;
  geoTarget: string;
  pickup: string;
  productb: string;
  productc: string;
  funding: string;
  channel: string;
  platform: string;
  startDate: string;
  endDate: string;
  totalDays: number;
  rate: string;
  tradingModel: string;
  netRate: number;
  campaignBudget: number;
  clientBudget: number;
  ioRegion: string;
  ioLi: string;
  xRate: number;
  marginPerc: number;
  plannedRevenue: number;
  campaignBudget$: number;
  margin$: number;
  totalBudget$: number;
  fees: number;
  totalInvestment: number;
  ctr: number;
  plannedConversions: number;
  totalImpressions: number;
  totalClicks: number;
  conversions: number;
  mediaCpaGoal: number;
  clientCpaGoal: number;
  dailySpend: number;
  totalRevenue: number;
  cosPercLimit: number;
  roiPercLimit: number;

  constructor() {
    this.publisher = '';
    this.producta = '';
    this.targetinga = '';
    this.targetingb = '';
    this.campaign = '';
    this.geoTarget = '';
    this.pickup = '';
    this.productb = '';
    this.productc = '';
    this.funding = '';
    this.channel = '';
    this.platform = '';
    this.startDate = '';
    this.endDate = '';
    this.totalDays = undefined;
    this.rate = '';
    this.tradingModel = '';
    this.netRate = undefined;
    this.campaignBudget = undefined;
    this.clientBudget = undefined;
    this.ioRegion = '';
    this.ioLi = '';
    this.xRate = undefined;
    this.marginPerc = undefined;
    this.plannedRevenue = undefined;
    this.campaignBudget$ = undefined;
    this.margin$ = undefined;
    this.totalBudget$ = undefined;
    this.fees = undefined;
    this.totalInvestment = undefined;
    this.ctr = undefined;
    this.plannedConversions = undefined;
    this.totalImpressions = undefined;
    this.totalClicks = undefined;
    this.conversions = undefined;
    this.mediaCpaGoal = undefined;
    this.clientCpaGoal = undefined;
    this.dailySpend = undefined;
    this.totalRevenue = undefined;
    this.cosPercLimit = undefined;
    this.roiPercLimit = undefined;
  }
}
